version: "3" # specify docker-compose version

# Define the services/containers to be run
services:
  client:
    build: ./client
    ports:
      - "80:4200"
  server: # name of the first service
    build: ./server # specify the directory of the Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_DB_URL=mongodb://database
      - DB_NAME=MyStore
    links:
      - database
    depends_on:
      - database
  database: # name of the third service
    image: mongo:4.2.3 # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
  mongo-seed:
    build: ./server/seed
    links:
      - database